version: "3.3"
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    restart: always
    depends_on:
      - db
      - etherpad
      - mail
    networks:
      - backend
      - frontend

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always  
    depends_on:
      - api
    networks:
      - frontend

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    networks:
      - backend

  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    networks:
      - backend

  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
    networks:
      - backend

networks:
  backend:
  frontend:
